on:
  push:
    branches: master
  workflow_dispatch:
    
jobs:
  build-and-package:
    name: Build nesto-serialproxy debian package
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN: arm-unknown-linux-gnueabi

    steps:
    - run: /opt/crosstool-ng/x-tools/${TOOLCHAIN}/bin >> $GITHUB_PATH
    - uses: actions/checkout@v2

    - name: Install cross-toolchain
      run: |
        ./scripts/install-cross-toolchain-armhf.sh

    - name: Run make
      run: |
        make CC=${TOOLCHAIN}-gcc CXX=${TOOLCHAIN}-g++

    - name: Upload Artifact - sersniff utility
      uses: actions/upload-artifact@v2
      with:
        name: nesto-serialproxy
        path: |
          sersniff