name: Build container
on:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build-container.yml'
    branches: master
  workflow_dispatch:

env:
  # used as the cross-toolchain release to be included into the image
  TOOLCHAIN_RELEASE: rpi-5.10.y

jobs:
  build-container:
    runs-on: 'ubuntu-20.04'
    steps:
      - 
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/serial-proxy-dev:latest,ghcr.io/${{ github.repository_owner }}/serial-proxy-dev:${{ env.TOOLCHAIN_RELEASE }}
          context: .devcontainer
          build-args: TOOLCHAIN_RELEASE=${{ env.TOOLCHAIN_RELEASE }}