name: Build tcpflow-gg
on:
  push:
    paths-ignore:
      - '.devcontainer/**'
    branches: master
  workflow_dispatch:

jobs:
  build-and-package:
    name: Build nesto-serialproxy debian package
    runs-on: 'ubuntu-20.04'
    container:
      image: ghcr.io/${{ github.repository_owner }}/serial-proxy-dev:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    
    steps:
    - run: echo /opt/crosstool-ng/x-tools/${TOOLCHAIN}/bin >> $GITHUB_PATH
    - uses: actions/checkout@v2

    - name: Build the cli utility
      run: |
        CPPFLAGS=-I$STAGING_DIR/usr/local/include/ LINKFLAGS="-L$STAGING_DIR/usr/local/lib" make CC=${TOOLCHAIN}-gcc CXX=${TOOLCHAIN}-g++

    - name: Build the greengrass package
      run: |
        mkdir -p greengrass/build
        cd greengrass/build
        CC=${TOOLCHAIN}-gcc CXX=${TOOLCHAIN}-g++ LDFLAGS="-L$STAGING_DIR/usr/local/lib" /tmp/cmake/bin/cmake "-DCMAKE_CXX_FLAGS=-I$STAGING_DIR/usr/local/include/" "-Daws-greengrass-core-sdk-c_DIR=${STAGING_DIR}/usr/local/lib/cmake/aws-greengrass-core-sdk-c/" ..
        make

    - name: Upload Artifact - sersniff utility
      uses: actions/upload-artifact@v2
      with:
        name: nesto-serialproxy
        path: |
          sersniff
          greengrass/build/serialproxy-gg

    - name: Release via gh releases with latest tag
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: false
        title: SerialProxy - Latest Binary Release
        files: |
          sersniff
          greengrass/build/serialproxy-gg